apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-cache-pvc
  labels:
    app: vllm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  # 使用我们配置的 local-path，存储在 /raid/tmpdata
  resources:
    requests:
      storage: 50Gi  # 根据模型大小调整，Llama-3.2-1B 约需 5-10GB，7B 约需 20-30GB
