# SGLang Serving for Llama-3.2-1B-Instruct
# A complete configuration file, including Deployment and Service
# Note: meta-llama/Llama-3.2-1B-Instruct is a gated repo, requires HF_TOKEN

---
# Secret needs to be created from environment variable, do not hardcode token
# Create command: kubectl create secret generic hf-token-secret --from-literal=token="$HF_TOKEN" -n <namespace>
# Or: kubectl create secret generic hf-token-secret --from-env-file=<(echo "token=$HF_TOKEN") -n <namespace>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sglang-llama-32-1b-pod
  labels:
    app: sglang
    model: llama-32-1b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sglang
      model: llama-32-1b
  template:
    metadata:
      labels:
        app: sglang
        model: llama-32-1b
    spec:
      runtimeClassName: nvidia
      containers:
      - name: sglang-server
        image: lmsysorg/sglang:v0.5.6.post2-runtime
        command:
        - python3
        - -m
        - sglang.launch_server
        args:
        - --model-path
        - meta-llama/Llama-3.2-1B-Instruct
        - --host
        - "0.0.0.0"
        - --port
        - "8000"
        - --mem-fraction-static
        - "0.2"  # Use 20% of GPU memory (same as vLLM for consistency)
        - --trust-remote-code
        env:
        - name: HF_HOME
          value: "/models/hub"
        - name: TRANSFORMERS_CACHE
          value: "/models/hub"
        - name: HF_HUB_CACHE
          value: "/models/hub"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
        ports:
        - containerPort: 8000
          name: http
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: 8Gi
          requests:
            nvidia.com/gpu: 1
            memory: 6Gi
        volumeMounts:
        - name: models
          mountPath: /models
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 3600
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 1800
          timeoutSeconds: 3
      volumes:
      - name: models
        hostPath:
          path: /models  # Path in k3d container, corresponds to /raid/models on host
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: sglang-llama-32-1b-service
  labels:
    app: sglang
    model: llama-32-1b
spec:
  type: ClusterIP
  selector:
    app: sglang
    model: llama-32-1b
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
